### ISSUE TITLE
Express Validator

### ISSUE THREAD

**Issue by mani9896** [pankajkumarbij/easy-job-intern#92] opened 2021-03-13 15:38 UTC
## Want to add express validator to validate form data at backend for POST signin and signup request.

#Please let me contribute for this feature

**Comment by pankajkumarbij** [comment] 2021-03-13 16:41
@mani9896 Thanks for opening an issue.

Wait for confirmation after that you can work on this issue if confirmed.

**Comment by pankajkumarbij** [comment] 2021-03-14 12:21
@mani9896 Go ahead

**Comment by pankajkumarbij** [comment] 2021-03-20 10:28
@mani9896 Are you working on it?

**Comment by mani9896** [comment] 2021-03-20 10:48
Hey sorry got a little busy in some personal things , please give me some time I'm working on it

**Comment by pankajkumarbij** [comment] 2021-03-20 11:14
@mani9896 ok ok 

before making a PR first pull all the changes from the original repo because there are many PR merged after you forked.

After pulling all the changes and update your work check that the project is working fine or not.

**Comment by pankajkumarbij** [comment] 2021-03-28 16:58
@mani9896 Ok thanks for opening an issue.
I am closing this issue because you are not able to complete it and we also not need this feature at this time.

**Closed as completed by pankajkumarbij** 2021-03-28 16:58 UTC
Labels: GSSOC21, Level1
